#!/bin/bash

install() {
  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # prepare vars
  local name="headscale"
  # files
  local tmp_file="$name"
  local bin_file="$tmp_file"

  # prepare context
  cd $tmp_dir

  # reference: https://github.com/juanfont/headscale/releases
  # example:
  #   https://github.com/juanfont/headscale/releases/download/v0.16.4/headscale_0.16.4_darwin_amd64
  #   https://github.com/juanfont/headscale/releases/download/v0.16.4/headscale_0.16.4_darwin_arm64
  # generate url
  local url="https://github.com/juanfont/headscale/releases/download/$PACKAGE_CORE_VERSION/${name}_${PACKAGE_CORE_VERSION#v}_${platform}_${arch}"
  log::debug "[package][$name][$kernel][$arch] url: $url"

  # download
  os::download $tmp_file $url

  # make executable
  chmod 755 $tmp_file

  # install
  sudo mv $bin_file $usr_bin_dir

  # clean
  rm -rf $tmp_dir
}

export -f install
